# Generated by Django 3.1.3 on 2020-12-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='added_to_shop',
            field=models.BooleanField(default=False),
        ),
    ]
