# Generated by Django 3.1.3 on 2020-12-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Order', '0002_auto_20201229_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='couponcode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
